### ISSUE TITLE
Add Risks Section? 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/docs#4]
Thoughts on adding a `risks` section to the root or under the `lenders` page? 

One of the things that always scares me away from protocols is when the risk vectors are not properly outlined and explained. 

AAVE has a risks section https://docs.aave.com/risk/
Maple has risks - https://maplefinance.gitbook.io/maple/additional-links/risks#smart-contract-risk

**Comment by jordanalexandermeyer** [comment]
Great call:
https://docs.porter.finance/portal/resources/risks
