### ISSUE TITLE
Use numbers in bond description that will help users understand our protocol 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/docs#5]
> The interest earned on a zero-coupon bond is an [imputed interest](https://www.investopedia.com/terms/i/imputedinterest.asp), meaning that it is an estimated interest rate for the bond and not an established interest rate. For example, a bond with a face amount of $20,000, that matures in 20 years, with a 5.5% yield, may be purchased for roughly $6,855. At the end of the 20 years, the investor will receive $20,000. The difference between $20,000 and $6,855 (or $13,145) represents the [interest that compounds](https://www.investopedia.com/terms/c/compoundinterest.asp) automatically until the bond matures. Imputed interest is sometimes referred to as "phantom interest."

These numbers could be adjusted to better represent what a porter bond would look like. IMO this would help to facilitate understanding of our protocol. 

(Example, 10,000 bonds with a face value of $1 that matures in 3 years)

**Comment by jordanalexandermeyer** [comment]
Good call
https://github.com/porter-finance/docs/commit/a0719c2ce005f7b6be774a948e1fb237887dce5b
