### ISSUE TITLE
Use USDC instead of $? 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/docs#6]
https://docs.porter.finance/portal/participants/lenders/how-to-lend

I think it would be more clear & accurate to use stablecoins in the examples instead of dollars. 

For example instead of 
> Therefore, the lender purchases 100,000 bonds for $95,000 which can be redeemed at maturity for $100,000.

saying 
> Therefore, the lender purchases 100,000 bonds for 95,000 USDC which can be redeemed at maturity for 100,000 USDC. 

Thoughts?

**Comment by jordanalexandermeyer** [comment]
Good idea. Do you think I should update the options pages too?
https://docs.porter.finance/portal/financial-concepts/convertible-bonds/put-options

**Comment by RusseII** [comment]
> Good idea. Do you think I should update the options pages too?
 
Yes

**Comment by jordanalexandermeyer** [comment]
It was much easier to understand when I removed USDC and used $ for everything so that's what I ended up doing.
