### ISSUE TITLE
Clarification regarding borrow token units

### ISSUE THREAD

**Issue by rootulp** [porter-finance/docs#7]
I have a suggestion for clarifying these docs:

> Face value - The amount the bond will be worth at maturity. The face value of Porter bonds is always 1 of the borrow token. For example, say an investor purchases a bond at $0.83, and another investor buys the same bond later when it is $0.9. When the bond matures, both investors will receive the $1 face value of the bond.

[source](https://docs.porter.finance/portal/financial-concepts/zero-coupon-bonds/characteristics-of-bonds).

This section says the face value of the bond is 1 borrow token but uses $ dollars for the remainder of the section. I think it's worth clarifying that in this example 1 borrow token == $1.

**Comment by jordanalexandermeyer** [comment]
> I have a suggestion for clarifying these docs:
> 
> > Face value - The amount the bond will be worth at maturity. The face value of Porter bonds is always 1 of the borrow token. For example, say an investor purchases a bond at $0.83, and another investor buys the same bond later when it is $0.9. When the bond matures, both investors will receive the $1 face value of the bond.
> 
> [source](https://docs.porter.finance/portal/financial-concepts/zero-coupon-bonds/characteristics-of-bonds).
> 
> This section says the face value of the bond is 1 borrow token but uses $ dollars for the remainder of the section. I think it's worth clarifying that in this example 1 borrow token == $1.

Great callout. The introduction of the "borrow token" is confusing for an end user so I removed it. All users need to know is that the face value is $1 because we are only allowing stablecoins to be used as the "borrow token" at launch.
